from ai_engine.agents.orchestrator import orchestrator_node
from ai_engine.agents.data_janitor import janitor_node
from ai_engine.graph.state import GraphState

# 1. Define the initial state with a specific instruction
state = GraphState(
    user_intent="Clean this sales data. Drop any rows where 'Amount' is not a valid number. Fill missing 'Customer_Name' with 'Unknown'. Convert 'Date' to proper datetime format.",
    raw_file_path="data/uploads/messy_sales.csv",
    clean_file_path=None,
    data_metadata=None,
    janitor_code=None,
    execution_error=None,
    retry_count=0,
    plotly_config=None,
    analytical_summary=None
)

# 2. Run the Orchestrator to get the metadata
print("\n[STARTING TEST]")
state.update(orchestrator_node(state))

# 3. Run the Janitor to write and execute the code
state.update(janitor_node(state))

# 4. Print the final results
print("\n--- CODE GENERATED BY GEMINI ---")
print(state["janitor_code"])

print("\n--- METADATA AFTER CLEANING ---")
print(state["data_metadata"])

if state.get("execution_error"):
    print(f"\n--- ERROR --- \n{state['execution_error']}")